### ISSUE TITLE
BCMtools-0.1.0 build fails during Haddock stage

### ISSUE THREAD

**Issue by peti** [kaizhang/HiC#1]
Citing from http://hydra.cryp.to/build/787640/log/raw:

```
src/BCM/DiskMatrix.hs:111:26: parse error on input ‘!’
```

**Comment by kaizhang** [comment]
7354a52bc129946e53652f52a517947e178e1b38

**Comment by peti** [comment]
Will you release a new version to Hackage?

**Comment by kaizhang** [comment]
Yes, maybe next week.

**Comment by peti** [comment]
OK. I'll remove the package from the NixOS distribution for the time being then.

**Comment by kaizhang** [comment]
@peti I've uploaded a new version. Thanks!
